name: Auto Update Subscriptions

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Decode SESSION_B64 and restore session
      run: |
        echo "${{ secrets.SESSION_B64 }}" | base64 --decode > session.session
        echo "SESSION_B64 decoded and session.session restored."

    - name: Run script
      env:
        API_ID: ${{ secrets.API_ID }}
        API_HASH: ${{ secrets.API_HASH }}
        PHONE_NUMBER: ${{ secrets.PHONE_NUMBER }}
      run: python main.py

    - name: Commit & Push
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git add clash_subscribe.yaml subscribe_base64.txt unique_nodes.txt
        git commit -m "Auto update subscription files" || echo "No changes"
        git push
