name: Auto Update Subscriptions

on:
  schedule:
    - cron: '0 * * * *'  # 每小时执行一次
  workflow_dispatch:  # 也支持手动触发

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run script
      env:
        _k1: ${{ secrets._k1 }}
        _k2: ${{ secrets._k2 }}
        _k3: ${{ secrets._k3 }}
      run: python main.py

    - name: Commit & Push updates
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git add wxx.yaml sub wxx.json  # 修改为你的文件名
        git commit -m "Auto update subscription files" || echo "No changes"
        git push
